// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-G4IsNkVSmYHyCNE-NQ8bmohqvbVo6-Y',
    appId: '1:1055739675659:android:75282e812d3ea97469f30e',
    messagingSenderId: '1055739675659',
    projectId: 'akhder-2e6f9',
    storageBucket: 'akhder-2e6f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZRANGkRkDtNUEOCq332USsBQ7i6EaB64',
    appId: '1:1055739675659:ios:f49deed9a52d873d69f30e',
    messagingSenderId: '1055739675659',
    projectId: 'akhder-2e6f9',
    storageBucket: 'akhder-2e6f9.appspot.com',
    androidClientId: '1055739675659-0t5leo4e1back1ss47e42mnrdmqjhbdb.apps.googleusercontent.com',
    iosClientId: '1055739675659-va7bcbc6f40h7aubo72dva6e12gksjvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.akhder',
  );

}